### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by dylan-vv** [CitiesSkylinesMultiplayer/CSM#10]
I really like to play with my friend on this game but im not able to install maybe can u make a tutorial or tell me what i did wrong?
https://gyazo.com/68d170254d6185605b7b2a53383a7d13
https://gyazo.com/62bcaea36b2a208ef6c20194b998774c

**Comment by dylan-vv** [comment]
Also i dont have any files in the folder CSM

**Comment by Breadabix** [comment]
You can remove the first 5 errors by manually copying some .dll files that are included in the download, but the last 5 errors are caused by the need for .dll files not included in the download, so more files need to be added to github before it is installable. Atleast thats what me and a friend can understand from trying to install this.

**Comment by Breadabix** [comment]
Update: Me and my friend have managed to solve 4 of the 5 remaining errors, however csm.dll is proving to be an issue, the mod doesnt work at all without it and me nor my friend can find it anywhere.

**Comment by Breadabix** [comment]
I cloned and downloaded the mod from github and the csm.dll file and a couple of others werent included. Is there a proper download im not aware of or just got unlucky?

**Comment by DominicMaas** [comment]
The mod now has continuous integration setup. On every commit and pull request a new version will be built. A link to this (and instructions) can be seen on the readme page. The CI builds contain all the required DLLs that you will need (alongside an install script).
