### ISSUE TITLE
Zoning not synced correctly

### ISSUE THREAD

**Issue by matthijsthoolen** [CitiesSkylinesMultiplayer/CSM#172]
**Describe the bug**

**To Reproduce**
1. Play  and zone some districts, maybe on a area
2. At the other player not everything is zonbed
3. Buildings get build and removed as if their is no zone (or the zone is removed

**Expected behavior**
Zoning is correctly synced (just normal residential zoning)

**Screenshots**
My situation, fully zoned. But buildings keep getting removed. 
![image](https://user-images.githubusercontent.com/1309536/77949473-4a5eb300-72c7-11ea-8406-b9909791f57c.png)

Situation for the other player
![image](https://user-images.githubusercontent.com/1309536/77949614-898d0400-72c7-11ea-8dab-43ef3f7f93bd.png)
![image](https://user-images.githubusercontent.com/1309536/77949629-93166c00-72c7-11ea-9990-30d42cf09e77.png)

**Active DLCs**
- After dark
- Carols, candles and candy
- Green Cities
- Industries
- Mass Transit
- Match Day
- Pearls from the east
- Snowfall
- Sunset Harbor

**Active mods**
- This mod
- 25 tiles mod w correct pricing
- Mod Achievement Enabler
- Unlimited soil
- Precision engineering

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 2003.3.0.0
- Game version: 1.13.0-f7

**Additional context**

**Comment by bdeetz** [comment]
Also experiencing this with no DLC and no other mods.

update: it seems to trigger when I zone blocks rapidly.

update 2: because this is udp and I'm on wifi, I'm wondering if this might be as simple as dropped packets.

**Comment by Al-Hoff** [comment]
I have also been experiencing problems with zoning sync on CSM 2003.3.0 No Mods, quite a few DLCs. I set up a new game yesterday to test out when my friend and I would become out of sync. I did not gather a clear conclusion on what triggers desynchronous events to happen.. However we ran into less problems and had to /sync less when we would slow down how much we zone instead of rapid firing over a bunch of tiles.

I was hardwired into my router during this game. Client is also on wired. I have had successful (no issue) games over WiFi before the sunset harbor release.

**Comment by matthijsthoolen** [comment]
We had less trouble when the game-speed was set to normal.

**Comment by andrelec1** [comment]
same here

**Comment by Revilum** [comment]
Hypnotic pointed out that if a player leaves then the issue gets resolved.
