### ISSUE TITLE
Founded issues/bugs

### ISSUE THREAD

**Issue by Banas921** [CitiesSkylinesMultiplayer/CSM#251]
Hi,
I have and found some issues.  The biggest and main issue is sync with roads. Bulding roads works on both computers (host/client), but if any of us delete any road second person didnt see any changes. If host will delete road and after that me as client will /sync after that I will see all of changes.
Using TM:PE on client computer didnt make any changes on host game.
Placing/removing buildings works normaly.
If we would found something more, I will update my post.

**Comment by joaogl** [comment]
Hey,

I’m not a pro here but mods that change the game logic or add logic are not supported yet by the mod which is why TMPE is not synced for you.
Regarding the roads I would probably ask you first to disable all mods besides CSM and test that again, my guess is that a mod is messing with CSM.

thanks

**Comment by kaenganxt** [comment]
As joaogl said, disable all other mods and try again. If any issues are still present afterwards, reopen this issue with the correct bug report template.
